parent=keycloak.v2
import=common/keycloak
stylesCommon=vendor/patternfly-v5/patternfly.min.css vendor/patternfly-v5/patternfly-addons.css
styles=css/styles.css css/wallet.css
scripts=js/theme.js
darkMode=false
meta=viewport==width=device-width,initial-scale=1
